#include <iostream>
using namespace std;

/*❗ Görev

Kullanıcıdan bir adet tam sayı N alın.
Program şu işlemleri pointer kullanarak gerçekleştirsin:

1. Dinamik Dizi Oluşturma

int* türünde bir pointer ile
N elemanlı bir dizi dinamik olarak oluşturun (new int[N]).

2. Kullanıcıdan Değerleri Pointer ile Alma

Kullanıcıdan N tane sayı alın.

Bu sayıları yalnızca pointer aritmetiği (örnek: *(ptr + i)) kullanarak diziye yazın.

3. Diziyi Pointer ile Yazdırma

Bir for döngüsü içinde:

Diziyi pointer ile gezinerek ekrana yazdırın.

Dizi elemanına erişirken yine *(ptr + i) kullanın.

4. Dizideki En Büyük Elemanı Bulan Fonksiyon

Aşağıdaki özelliklere sahip bir fonksiyon yazın:

int* enBuyukAdres(int* dizi, int uzunluk);


Fonksiyon, dizideki en büyük sayının adresini döndürsün.

main() içinde bu fonksiyonu çağırın.

Dönen pointer üzerinden en büyük değeri ekrana yazdırın.

5. Pointer Null Kontrolü

Fonksiyondan dönen pointer’ın nullptr olup olmadığını kontrol edin.

Boş değilse değeri yazdırın.

6. Belleği Temizleme

En sonda:

Diziyi delete[] ile silin.

Pointer’ı nullptr yapın.

Pointer’ın artık boş olduğunu ekrana yazdırın.*/

int main(){

    
}